version: '3.9'

services:
  db:
    image: postgres:16
    container_name: jornal_db
    environment:
      POSTGRES_DB: jornal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
